webtalk_init -webtalk_dir /home/brycetherower/Documents/vivado/ECE2029_Metronome/ECE2029_Metronome.sim/sim_1/behav/xsim/xsim.dir/metronome_debug_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  3 23:16:41 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7535738a-1f3b-449d-8bad-95d43580adab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c97e772705704cf2b060f853a6eec57f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "37" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 19.04" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1776.191 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 s" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "625.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115324_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4016699646 -regid "" -xml /home/brycetherower/Documents/vivado/ECE2029_Metronome/ECE2029_Metronome.sim/sim_1/behav/xsim/xsim.dir/metronome_debug_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/brycetherower/Documents/vivado/ECE2029_Metronome/ECE2029_Metronome.sim/sim_1/behav/xsim/xsim.dir/metronome_debug_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/brycetherower/Documents/vivado/ECE2029_Metronome/ECE2029_Metronome.sim/sim_1/behav/xsim/xsim.dir/metronome_debug_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
